config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('polls/', include('polls.urls')),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('', photo_list,name='photo_list'),
    path('detail/<int:pk>/',DetailView.as_view(model=Photo,template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:quiz_id>/', views.quiz, name='quiz'),
    path('<int:quiz_id>/check_answer/', views.check_answer, name='check_answer'),
    path('completed/', views.completed, name='completed'),
    #path('incorrect/', views.incorrect, name='incorrect'),
    path('next_quiz/<int:quiz_id>/', views.next_quiz, name='next_quiz'),

]

polls/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime

class Quiz(models.Model):
    question = models.CharField(max_length=200)
    image = models.ImageField(upload_to='quiz_images/', blank=True, null=True)
    is_text_answer = models.BooleanField(default=False)
    is_date_answer = models.BooleanField(default=False)
    points = models.PositiveIntegerField(default=1)
    date_asked = models.DateTimeField(default=timezone.now,editable=False)

    def check_answer(self, user_answer):
        if self.is_text_answer:
            correct_answer = self.answers.filter(is_correct=True).first()
            #return user_answer.lower() == datetime.now().strftime('%Y-%m-%d').lower()
            if correct_answer:
                return user_answer.lower() == correct_answer.text.lower()
            else:
                return False
        #elif self.is_date_answer:
        #    # 날짜 응답을 날짜 형식으로 변환
        #    user_date = datetime.now().date()
        #    correct_date = self.answers.filter(is_correct=True).first().date_answered.date() if self.answers.filter(is_correct=True).first() else None
        #    return user_date == correct_date if correct_date else False
        else:
            correct_answer = self.answers.filter(is_correct=True).first()
            return user_answer.lower() == correct_answer.text.lower() if correct_answer else False
            #pass
class Answer(models.Model):
    text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)
    image = models.ImageField(upload_to='answer_images/', blank=True, null=True)
    is_text_answer = models.BooleanField(default=False)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='answers', null=True, blank=True)

    def __str__(self):
        return self.text


class UserAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)  # Assuming User is your user model
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='useranswer', null=True)
    selected_answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)  # Add Answer relationship here
    #selected_answer_text = models.TextField(blank=True)
    is_correct = models.BooleanField(default=False)
    image = models.ImageField(upload_to='useranswer_images/', blank=True, null=True)
    date_answered = models.DateTimeField(default=timezone.now)
    score = models.PositiveIntegerField(default=0)
    #def save(self, *args, **kwargs):
     #   if not self.quiz:
      #      self.quiz = self.quiz
       # super().save(*args, **kwargs)
    def save(self, *args, **kwargs):

        if not self.quiz:
            self.quiz = self.quiz

        super().save(*args, **kwargs)

polls/forms.py
from django import forms
from .models import Quiz, Answer

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['question', 'image']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'is_correct', 'image']
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['text'].widget.attrs.update({'style': 'width: 150px; height: 150px;'})
        #self.fields['image'].widget.attrs.update({'style': 'width: 30px; height: 30px;'})
        if self.instance and self.instance.quiz_id and Quiz.objects.filter(id=self.instance.quiz_id, is_text_answer=True).exists():
            self.fields['text'] = forms.CharField(max_length=100, label='Your Answer')
            del self.fields['image']
        else:
            self.fields['image'] = forms.ImageField(label='Your Answer Image')
            del self.fields['text']


class AnswerFormText(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'is_correct', 'image']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }

polls/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Quiz, Answer, UserAnswer
from django.db.models import Max
from .forms import QuizForm, AnswerForm, AnswerFormText
from django.utils import timezone
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser

def quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    answers = Answer.objects.filter(quiz=quiz)
    form_class = AnswerFormText if quiz.is_text_answer else AnswerForm
    form = form_class()
    return render(request, 'polls/quiz.html', {'quiz': quiz, 'answers': answers})
def index(request):

    first_quiz = Quiz.objects.first()
    #return redirect('polls:quiz', quiz_id=first_quiz.id)

    #퀴즈 리스트 보여주기
    latest_quiz_list = Quiz.objects.all().order_by('-id')[:5]
    context = {'latest_quiz_list': latest_quiz_list}
    return render(request, 'polls/index.html', context)

@login_required(login_url='/polls/')
def check_answer(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    user = request.user

    if user.is_anonymous:
        user = AnonymousUser()

    if quiz.is_text_answer:
        #selected_answer_text = request.POST.get('answer_text', '')
        #is_correct = quiz.check_answer(selected_answer_text)
        is_correct = quiz.check_answer(request.POST.get('answer_text', ''))
    else:
        selected_answer_id = request.POST.get('answer', '')
        selected_answer = get_object_or_404(Answer, id=selected_answer_id)
        is_correct = selected_answer.is_correct

    question_score = quiz.points if is_correct else 0

    user_answer, created = UserAnswer.objects.get_or_create(user=user, quiz=quiz)
    #user_answer.selected_answer_text = selected_answer_text if quiz.is_text_answer else ''
    user_answer.selected_answer_text = request.POST.get('answer_text', '') if quiz.is_text_answer else ''
    user_answer.is_correct = is_correct
    user_answer.score = question_score
    user_answer.date_answered = timezone.now()
    user_answer.save()
    print(f"user: {user}")
    print(f"quiz: {quiz}")
    print(f"is_correct: {is_correct}")
    print(f"user_answer: {user_answer}")

    total_score = UserAnswer.objects.filter(user=user).aggregate(Sum('score'))['score__sum']

    next_quiz = Quiz.objects.filter(id__gt=quiz_id, useranswer__user=user).first() if user.is_authenticated else None

    if next_quiz:
        return redirect('polls:quiz', quiz_id=next_quiz.id)
    else:
        return render(request, 'polls/completed.html', {'total_score': total_score})

def next_quiz(request):
    user = request.user
    # Get the maximum quiz ID that the user has already answered
    max_answered_quiz_id = UserAnswer.objects.filter(user=user).aggregate(Max('quiz__id'))['quiz__id__max']

    # If the user hasn't answered any quizzes yet, max_answered_quiz_id will be None
    # In that case, we set it to -1 to make the filter below work
    if max_answered_quiz_id is None:
        max_answered_quiz_id = -1

    #next_quiz = Quiz.objects.filter(id__gt=max_answered_quiz_id).exclude(useranswer__isnull=True).first()
    #next_quiz = Quiz.objects.filter(id__gt=max_answered_quiz_id).order_by('id').first()
    next_quiz = Quiz.objects.filter(id__gt=max_answered_quiz_id).exclude(useranswer__user=user).first()
    print(f"max_answered_quiz_id: {max_answered_quiz_id}")
    print(f"next_quiz: {next_quiz}")
    if next_quiz:
        return redirect('polls:quiz', quiz_id=next_quiz.id)
    else:
        return redirect('polls:completed')
@login_required(login_url='/polls/')
def completed(request,total_score=None):
    user = request.user
    total_score = 0
    user_answers = []

    if user.is_authenticated:
        user_answers = UserAnswer.objects.filter(user=user)
        total_score = UserAnswer.objects.filter(user=user).aggregate(Sum('score'))['score__sum']

    return render(request, 'polls/completed.html', {'total_score': total_score, 'user_answers': user_answers})

polls/templates/polls/completed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quiz completed</title>
</head>
<body>
    {% block content %}
        <h2>퀴즈 완료!</h2>
        <p>총 점수: {{ total_score }}점</p>
        {% if next_quiz %}
            <a href="{% url 'polls:next_quiz' %}">Next Quiz</a>
        {% endif %}
        <br>
            <a href="/">홈으로 돌아가기</a>
        <br>
            <a href="{% url 'polls:index' %}">문제 리스트 보기</a>
        <ul>
            {% for user_answer in user_answers %}
                <li>{{ user_answer.quiz.question }} - {{ user_answer.score }}점</li>
            {% endfor %}
        </ul>
    {% endblock %}
</body>
</html>

polls/templates/polls/incorrect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Incorrect Answer</title>
</head>
<body>
    <h2>Your Incorrect Answers:</h2>
    <ul>
        {% for user_answer in incorrect_answers %}
            <li>{{ user_answer.quiz.question }}</li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_quiz_list %}
    <ul>
        {% for quiz in latest_quiz_list %}
        <li><a href="{% url 'polls:quiz' quiz.id %}">문제{{quiz.id}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>no polls are available.</p>
{% endif %}
<a href="/">홈으로 돌아가기</a>
</body>
</html>
</html>

polls/templates/polls/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
  <h2>{{ quiz.question }}</h2>
  {% if quiz.image %}
    <img src="{{ quiz.image.url }}" alt="Quiz Image">
  {% endif %}
  <form method="post" action="{% url 'polls:check_answer' quiz.id %}">
    {% csrf_token %}
    {% if quiz.is_text_answer %}
      <label>답:</label>
      <input type="text" name="answer_text" required>
    {% else %}
      {% for answer in answers %}
        <input type="radio" id="answer_{{ answer.id }}" name="answer" value="{{ answer.id }}">
        <label for="answer_{{ answer.id }}">{{ answer.text }}
        {% if answer.image %}
          <img src="{{ answer.image.url }}" alt="Answer Image">
        {% endif %}
        </label>
        <br>
      {% endfor %}
    {% endif %}
    <input type="submit" value="제출">
  </form>
  <li><a href="{% url 'polls:completed' %}">총 점수 보기</a>
      <a href="{% url 'polls:index' %}">문제 리스트 보기</a>
      <a href="/">홈으로 돌아가기</a></li>
{% endblock %}
</body>
</html>